example

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,8 +1,8 @@
 #!/bin/sh
 
-if [ ! -f "index.html" ]; then
-  echo "❌ index.html not found in root directory."
-  exit 1
-fi
+# if [ ! -f "index.html" ]; then
+#   echo "❌ index.html not found in root directory."
+#   exit 1
+# fi
 
 echo "✅ index.html found. Push allowed."
